seed: 0
mode: extract_and_save
model:
  name: 'facebook/dinov2-large' # 'facebook/dinov2-base' 'facebook/dinov2-large' openai/clip-vit-large-patch14
  patch_size: 14
  height: 518
  width: 518
  embed_dim: 1024
  shortest_edge: 518

device: 'cuda:0'

trainer:
  train_mode: 'pairwise' # pairwise, pointwise_class, pointwise_identity
  layer: 18
  batch_size: 256
  max_epoch: 16
  learning_rate: 1e-3
  num_workers: 8 # dataloader num_workers
  weight_decay: 0.0
  scheduler:
    step_size: 8
    gamma: 0.2
  loss:
    temperature: 0.07

dataset:
  name: 'ade20k'
  data_dir: "/workspaces/003/data/datasets/ade20k/1/"
  index: 10
  train_ratio: 0.8
  num_saved_patches: 512
  num_samples: 64 #sample #patches per epoch

data_extractor:
  cache_dir: '/workspaces/003/data/huggingface_cache/'
  batch_size: 1 # need to set to 1 for saving activations correctly
  activation_dir: '/workspaces/003/data/activations/${model.name}/'
  image_processor:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    shortest_edge: 518
    crop_size: [518, 518]
    normalize: true

probe:
  mode: 'quadratic' # diag_quadratic, quadratic, linear
  in_dim: 1024
  out_dim: 151
  rank: 100

  instance_seg:
      class_weight: 2.0
      mask_weight: 5.0
      dice_weight: 5.0
      num_queries: 100
      no_object_weight: 0.1

result_dir: "/workspaces/003/src/results/"
#output_dir: ${hydra:runtime.cwd}/../../data/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/
output_dir: ${hydra:runtime.cwd}/../../data/outputs/layer_${trainer.layer}_probe_${probe.mode}

hydra:
  run:
    dir: ${output_dir}

